import { useState } from 'react';
import { 
  Swords, Hexagon, Clock, Trophy, Zap, Star, ChevronRight, 
  ArrowLeft, Flame, Eye, Heart, Sparkles, Coins, Skull, 
  Shield, MessageCircle, Layers, Package, RotateCcw 
} from 'lucide-react';
import { CHARACTER_CLASSES, CAMPAIGN_ENCOUNTERS, getStoryOutcome } from './data/campaign';
import { CharacterClass, ActionChoice, RunState } from './types';

export default function App() {
  const [activeScreen, setActiveScreen] = useState<'home' | 'class_select' | 'encounter' | 'recap'>('home');
  const [run, setRun] = useState<RunState>({
     runId: '123', currentHp: 0, displayHp: 0, gold: 0, floorNumber: 1, turnCount: 0, isDead: false, isFinished: false, actionHistory: [], eventLog: [], inventory: [], pendingAnimations: []
  });
  const [combatLogs, setCombatLogs] = useState<{action: string; result: string; style: string}[]>([]);
  const [victoryState, setVictoryState] = useState(false);

  const startGame = (playerClass: CharacterClass) => {
     setRun({
       runId: 'start_123', playerClass, currentHp: 10, displayHp: 10, gold: playerClass.gold, floorNumber: 1, turnCount: 1, isDead: false, isFinished: false, actionHistory: [], eventLog: [], inventory: [], currentEncounter: CAMPAIGN_ENCOUNTERS[1], pendingAnimations: []
     });
     setCombatLogs([]);
     setVictoryState(false);
     setActiveScreen('encounter');
  }

  const handleAction = (choice: {text: string, style: any}) => {
     const outcome = getStoryOutcome(run.floorNumber, choice.style, run.playerClass?.id || '');
     setCombatLogs(prev => [...prev, {action: choice.text, result: outcome.narrativeOutcome, style: choice.style}]);
     const nextHp = Math.max(0, run.currentHp + outcome.playerHpChange);
     
     setRun(prev => ({
        ...prev,
        currentHp: nextHp,
        gold: prev.gold + outcome.goldAward,
        turnCount: prev.turnCount + 1,
        isDead: nextHp <= 0
     }));

     if (nextHp <= 0 || combatLogs.length >= 2) {
       setVictoryState(true);
     }
  };

  return (
    <div className="min-h-[100dvh] w-full bg-black flex items-center justify-center p-0 sm:p-4">
      <div className="w-full h-[100dvh] sm:max-w-[410px] sm:h-[820px] sm:max-h-[min(100dvh-2rem,820px)] bg-[#050B14] rounded-none sm:rounded-[48px] overflow-hidden border-0 sm:border-[12px] border-[#10192A] relative shadow-2xl flex flex-col font-sans">
         
         {/* NOTCH EMULATOR */}
         <div className="hidden sm:flex absolute top-0 left-1/2 -translate-x-1/2 w-40 h-7 bg-[#10192A] rounded-b-3xl z-50 items-center justify-center">
            <div className="w-14 h-1.5 bg-black/50 rounded-full" />
            <div className="w-2.5 h-2.5 bg-indigo-950 rounded-full ml-3" />
         </div>

         {/* 1. HOME SCREEN */}
         {activeScreen === 'home' && (
           <div className="flex-1 bg-[#090F16] flex flex-col items-center justify-center p-6 pt-12 pb-10 text-white relative overflow-hidden">
             <div className="absolute top-[20%] w-64 h-64 bg-cyan-900/20 rounded-full blur-[80px]" />
             
             <div className="relative z-10 w-full flex flex-col items-center">
               <div className="w-16 h-16 bg-gradient-to-br from-cyan-600 to-cyan-900 rounded-[20px] flex items-center justify-center mb-5 shadow-[0_0_30px_rgba(34,211,238,0.25)]">
                 <Swords className="text-white w-8 h-8" />
               </div>
               <h1 className="text-4xl font-extrabold mb-1 tracking-tight">Realm Explorer</h1>
               <div className="flex items-center space-x-2 text-cyan-500 text-[10px] tracking-[0.2em] font-mono mb-2">
                 <Hexagon className="w-3 h-3" />
                 <span>AGENTIC DUNGEON CRAWLER</span>
                 <Hexagon className="w-3 h-3" />
               </div>
               <p className="text-[#64748B] text-[11px] mb-8 text-center max-w-[200px]">Every encounter generated by Gemini AI in real time.</p>
               
               <div className="w-full bg-[#0F172A]/80 backdrop-blur-sm border border-[#1E293B] rounded-xl overflow-hidden mb-8 shadow-xl">
                 <div className="flex justify-between items-center px-4 py-2 border-b border-[#1E293B] bg-[#050B14]">
                   <div className="flex items-center space-x-2">
                     <div className="w-5 h-5 bg-blue-500 rounded-full" />
                     <span className="font-mono text-[10px] text-gray-400 tracking-wider">EXPLORER PROFILE</span>
                   </div>
                   <div className="flex items-center space-x-1">
                     <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full flex shrink-0 shadow-[0_0_5px_rgba(16,185,129,0.5)]" />
                     <span className="font-mono text-[10px] text-emerald-500">ACTIVE</span>
                   </div>
                 </div>
                 
                 <div className="grid grid-cols-3 divide-x divide-[#1E293B] text-center p-3">
                   <div className="flex flex-col items-center">
                     <Clock className="w-4 h-4 text-gray-500 mb-1" />
                     <div className="font-bold text-lg mb-0.5">3</div>
                     <div className="font-mono text-[9px] text-[#475569]">RUNS</div>
                   </div>
                   <div className="flex flex-col items-center">
                     <Trophy className="w-4 h-4 text-gray-500 mb-1" />
                     <div className="font-bold text-lg mb-0.5">4/5</div>
                     <div className="font-mono text-[9px] text-[#475569]">BEST DEPTH</div>
                   </div>
                   <div className="flex flex-col items-center">
                     <Zap className="w-4 h-4 text-gray-500 mb-1" />
                     <div className="font-bold text-lg mb-0.5">aggres</div>
                     <div className="font-mono text-[9px] text-[#475569]">STYLE</div>
                   </div>
                 </div>
                 
                 <div className="px-3 pb-3">
                   <div className="font-mono text-[9px] text-[#475569] mb-1.5">EARNED TITLES</div>
                   <div className="flex flex-wrap gap-1.5">
                     <div className="flex items-center space-x-1 border border-cyan-900/50 bg-cyan-950/20 text-cyan-300 text-[10px] px-2 py-1 rounded-full">
                       <Star className="w-3 h-3 text-cyan-500" /> <span>The Iron Warlord</span>
                     </div>
                     <div className="flex items-center space-x-1 border border-cyan-900/50 bg-cyan-950/20 text-cyan-300 text-[10px] px-2 py-1 rounded-full">
                       <Star className="w-3 h-3 text-cyan-500" /> <span>The Principled Dancer</span>
                     </div>
                   </div>
                 </div>
               </div>
               
               <div className="flex items-center space-x-2 text-[10px] font-mono text-gray-500 mb-2">
                 <div className="w-2 h-2 bg-emerald-400 rounded-full shadow-[0_0_5px_rgba(16,185,129,0.5)]" />
                 <span>Powered by <span className="text-cyan-400 font-bold">Gemini 2.0 Flash</span></span>
               </div>
               <button onClick={() => setActiveScreen('class_select')} className="w-full bg-gradient-to-r from-cyan-600 to-cyan-500 hover:from-cyan-500 hover:to-cyan-400 text-white rounded-full py-3.5 flex justify-center items-center font-bold text-sm shadow-lg mb-3">
                 <Swords className="w-4 h-4 mr-2" /> Enter the Dungeon <ChevronRight className="w-4 h-4 ml-1" />
               </button>
               <div className="text-[10px] font-mono text-[#334155] tracking-wider text-center">
                 AI-powered · Every run is unique · 5 floors deep
               </div>
             </div>
           </div>
         )}

         {/* 2. CLASS SELECT SCREEN */}
         {activeScreen === 'class_select' && (
           <div className="flex-1 bg-[#090F16] flex flex-col">
             <div className="px-4 pb-3 pt-12 border-b border-[#1E293B] shrink-0 flex items-center space-x-3 bg-[#090F16] z-10">
                <button onClick={() => setActiveScreen('home')} className="w-8 h-8 rounded-full bg-[#0F172A] flex items-center justify-center border border-[#1E293B]">
                  <ArrowLeft className="w-4 h-4 text-gray-400" />
                </button>
                <div className="flex flex-col">
                  <h2 className="text-white font-bold text-lg leading-tight">Choose Your Class</h2>
                  <div className="font-mono text-[9px] text-gray-500 tracking-widest uppercase mt-0.5">FLOOR 1 OF 5</div>
                </div>
             </div>
             
             <div className="p-4 flex-1 overflow-y-auto space-y-4">
                <p className="text-gray-400 text-xs mb-1">Your class shapes how the Dungeon Master builds every floor. Choose carefully.</p>
                
                {CHARACTER_CLASSES.map((cls) => (
                  <button key={cls.id} onClick={() => startGame(cls)} className="w-full text-left bg-[#0F172A] border border-[#1E293B] rounded-2xl p-4 relative">
                    <div className="flex justify-between items-start mb-2.5">
                      <div className="flex items-center space-x-3">
                        <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${
                          cls.id === 'blade_dancer' ? 'bg-red-950 text-red-500 border border-red-900/30' :
                          cls.id === 'ember_mage' ? 'bg-amber-950 text-amber-500 border border-amber-900/30' :
                          'bg-purple-950 text-purple-400 border border-purple-900/30'
                        }`}>
                          {cls.id === 'blade_dancer' && <Swords className="w-5 h-5" />}
                          {cls.id === 'ember_mage' && <Flame className="w-5 h-5" />}
                          {cls.id === 'shadow_rogue' && <Eye className="w-5 h-5" />}
                        </div>
                        <div className="flex flex-col items-start">
                          <h3 className="text-white font-bold text-base leading-none mb-1.5">{cls.name}</h3>
                          <span className={`text-[8px] font-mono px-1.5 py-0.5 rounded-full border leading-none font-bold ${
                            cls.id === 'blade_dancer' ? 'bg-red-950/60 text-red-400 border-red-900/50' :
                            cls.id === 'ember_mage' ? 'bg-amber-950/60 text-amber-400 border-amber-900/50' :
                            'bg-purple-950/60 text-purple-400 border-purple-900/50'
                          }`}>
                            {cls.id === 'blade_dancer' ? 'AGGRESSIVE' : cls.id === 'ember_mage' ? 'UNPREDICTABLE' : 'CAUTIOUS'}
                          </span>
                        </div>
                      </div>
                      <div className="flex items-center space-x-1 text-gray-400 font-mono text-[10px]">
                        <Heart className="w-3 h-3 text-red-600/80" /> <span className="font-bold text-white">{cls.hp} <span className="text-gray-500 font-normal">HP</span></span>
                      </div>
                    </div>
                    
                    <p className="text-[#64748B] text-[11px] mb-2 leading-relaxed">
                      {cls.name === 'Blade Dancer' ? 'A swift melee fighter who excels in rapid combos and precision strikes.' : 
                       cls.name === 'Ember Mage' ? 'A tactical spellcaster who prefers high-risk, high-reward arcane plays.' : 
                       'A careful infiltrator who weaponizes deception, patience, and escape routes.'}
                    </p>
                    <p className="text-[#475569] italic text-[11px] mb-3 font-serif">
                      "{cls.name === 'Blade Dancer' ? 'Trained in the lost arts of the Shadow Courts, blade dancers read the flow of combat like poetry.' : 
                        cls.name === 'Ember Mage' ? 'Ember Mages channel volatile fire magic — their power is immense, their control, questionable.' : 
                        'They say a Shadow Rogue was never truly in the room — just their reputation.'}"
                    </p>
                    
                    <div className="bg-[#090F16] border border-[#1E293B] rounded-xl p-2.5 mb-2.5 flex space-x-2">
                      <Sparkles className={`w-3.5 h-3.5 shrink-0 ${cls.id === 'blade_dancer' ? 'text-red-400' : cls.id === 'ember_mage' ? 'text-amber-400' : 'text-purple-400'}`} />
                      <p className="text-[10px] text-gray-400 leading-tight">
                        <span className={`font-mono font-bold mr-1 ${cls.id === 'blade_dancer' ? 'text-red-400' : cls.id === 'ember_mage' ? 'text-amber-400' : 'text-purple-400'}`}>
                          {cls.name === 'Blade Dancer' ? 'FLURRY:' : cls.name === 'Ember Mage' ? 'ARCANE BURST:' : 'VANISH:'}
                        </span>
                        {cls.name === 'Blade Dancer' ? 'Deal double damage on next strike, but take chip damage yourself.' : cls.name === 'Ember Mage' ? 'Area damage — needs one cooldown turn before reuse.' : 'Skip one encounter per floor with no HP cost.'}
                      </p>
                    </div>
                    
                    <div className="flex items-center space-x-1.5 text-[10px] text-gray-500 font-mono">
                      <Coins className="w-3.5 h-3.5 text-yellow-500/80" /> <span>Starting gold: <span className="text-yellow-500 font-bold">{cls.gold}</span></span>
                    </div>
                  </button>
                ))}
                <div className="pb-4" />
             </div>
             
             <div className="p-4 pb-8 bg-[#090F16] border-t border-[#1E293B] text-center shrink-0">
               <div className="py-3 rounded-xl border border-[#1E293B] bg-[#0F172A] font-mono text-[11px] font-semibold text-[#64748B]">
                 ↑ Select a class to begin ↑
               </div>
             </div>
           </div>
         )}
         
         {/* 3. ENCOUNTER VIEW */}
         {activeScreen === 'encounter' && (
           <div className="flex-1 bg-[#090F16] flex flex-col font-sans">
             {/* Progress / Status Header */}
             <div className="px-4 pb-4 pt-12 bg-[#090F16] border-b border-[#1E293B] shrink-0 z-10">
               <div className="flex justify-between items-center text-[10px] font-mono mb-1.5 text-gray-500">
                 <span className="tracking-widest flex items-center"><Layers className="w-3 h-3 mr-1 text-[#475569]"/> FLOOR {run.floorNumber} / 5</span>
                 <span>Turn {run.turnCount}</span>
               </div>
               <div className="flex space-x-1 mb-3">
                 {[1,2,3,4,5].map(i => (
                   <div key={i} className={`h-1 flex-1 rounded-full ${i <= run.floorNumber ? 'bg-cyan-600' : 'bg-[#1E293B]'}`} />
                 ))}
               </div>
               <div className="flex justify-between items-end">
                 <div className="font-mono flex flex-col">
                   <span className="text-[9px] text-[#475569] uppercase tracking-widest leading-none mb-1">YOUR HP</span>
                   <span className="text-red-400 font-bold text-sm leading-none">{run.currentHp} <span className="text-[#475569]">/ {run.playerClass?.maxHp}</span></span>
                 </div>
                 <div className="flex items-center space-x-1 text-yellow-500 font-mono text-[11px] border border-yellow-900/50 bg-[#282110] px-2.5 py-1 rounded-full font-bold">
                   <Coins className="w-3 h-3"/> <span>{run.gold}</span>
                 </div>
               </div>
               
               <div className="h-1.5 w-full bg-[#1E293B] rounded-full mt-3 overflow-hidden">
                 <div className="h-full bg-red-400 rounded-full" style={{width: `${(run.currentHp / (run.playerClass?.maxHp||10)) * 100}%`}} />
               </div>
             </div>
             
             {/* Entity Badge attached via sticky styling */}
             <div className="px-4 mt-3 shrink-0">
               <div className="bg-[#0F172A] border border-[#1E293B] rounded-t-xl rounded-b px-3 pt-2.5 pb-3">
                 <div className="flex justify-between items-start mb-2">
                   <div className="flex items-center space-x-2.5">
                     <div className="w-8 h-8 rounded-lg bg-red-950 flex items-center justify-center border border-red-900/40 shrink-0">
                       <Skull className="w-4 h-4 text-red-500" />
                     </div>
                     <div className="flex flex-col">
                       <h3 className="text-white font-bold text-sm leading-none mb-1.5">Golem Sentinel</h3>
                       <div className="flex items-center space-x-1.5 text-[8px] font-mono text-gray-500 tracking-wider font-bold">
                         <span className="text-red-400 border border-red-900/40 bg-red-950/40 px-1 py-0.5 rounded">COMBAT</span>
                         <span>·</span>
                         <span className="flex items-center text-yellow-500"><Zap className="w-2.5 h-2.5 mr-0.5" /> LV.3</span>
                       </div>
                     </div>
                   </div>
                   <div className="text-red-500 font-mono text-xs font-bold leading-none mt-1">
                     10<span className="text-red-900">/10</span>
                   </div>
                 </div>
                 
                 <div className="h-1.5 w-full bg-[#050B14] rounded-full overflow-hidden mt-1 relative border border-[#1E293B]">
                   {/* Thick blocky retro health bar */}
                   <div className="h-full bg-red-500 w-[95%] shadow-[0_0_10px_rgba(239,68,68,0.5)] border-r border-[#090F16]" />
                 </div>
               </div>
             </div>

             {/* Scrolling Content Log */}
             <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4 text-[13px] text-gray-300">
               <p className="leading-relaxed text-[#94A3B8]">
                 A massive stone construct blocks your descent into the second chamber. Its single eye pulses with ancient malice, scanning the corridor with mechanical precision. The air around it hums with barely restrained force — this guardian has waited centuries for someone to challenge it.
               </p>
               
               {combatLogs.map((log, i) => (
                 <div key={i} className="animate-fade-in pt-1">
                    <div className="text-red-400 font-mono text-[11px] font-bold mb-1.5 flex items-start">
                       <span className="w-1.5 h-1.5 bg-red-500 rounded-full shrink-0 mt-1 mr-2 shadow-[0_0_5px_rgba(239,68,68,0.8)]" />
                       <span>&gt; You: {log.action}</span>
                    </div>
                    <p className="text-[#94A3B8] leading-relaxed">
                      {log.result || "The construct stutters and recalibrates its mechanics."}
                    </p>
                 </div>
               ))}
               <div className="pb-4" />
             </div>
             
             {/* Dynamic Footer Controls */}
             <div className="p-4 sm:p-3 bg-[#090F16] border-t border-[#1E293B] shrink-0 pb-8 sm:pb-6 relative z-10">
               {victoryState ? (
                 <button onClick={() => setActiveScreen('recap')} className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl py-3 flex justify-center items-center font-mono uppercase text-xs tracking-wider shadow-[0_0_20px_rgba(5,150,105,0.2)]">
                   <Swords className="w-4 h-4 mr-2" /> Claim Victory
                 </button>
               ) : (
                 <div className="flex flex-col space-y-2">
                   <button onClick={() => handleAction({text: "Strike the eye", style: 'aggressive'})} className="w-full flex justify-between items-center border border-red-900/60 bg-red-950/20 hover:bg-red-950/30 rounded-full px-4 py-2.5">
                     <span className="text-white font-bold text-xs tracking-wide">Strike the eye</span>
                     <div className="flex items-center space-x-1 text-red-500 font-mono text-[9px] font-bold">
                       <Swords className="w-2.5 h-2.5" /> <span>ATTACK</span>
                     </div>
                   </button>
                   <button onClick={() => handleAction({text: "Seek a weakness in the joints", style: 'cautious'})} className="w-full flex justify-between items-center border border-amber-900/60 bg-amber-950/20 hover:bg-amber-950/30 rounded-full px-4 py-2.5">
                     <span className="text-white font-bold text-xs tracking-wide">Seek a weakness in the joints</span>
                     <div className="flex items-center space-x-1 text-amber-500 font-mono text-[9px] font-bold">
                       <Shield className="w-2.5 h-2.5" /> <span>DEFEND</span>
                     </div>
                   </button>
                   <button onClick={() => handleAction({text: "Taunt it into overextending", style: 'diplomatic'})} className="w-full flex justify-between items-center border border-cyan-900/60 bg-cyan-950/20 hover:bg-cyan-950/30 rounded-full px-4 py-2.5">
                     <span className="text-white font-bold text-xs tracking-wide">Taunt it into overextending</span>
                     <div className="flex items-center space-x-1 text-cyan-400 font-mono text-[9px] font-bold">
                       <MessageCircle className="w-2.5 h-2.5" /> <span>PARLEY</span>
                     </div>
                   </button>
                   <button onClick={() => handleAction({text: "Retreat and reassess", style: 'unpredictable'})} className="w-full flex justify-between items-center border border-purple-900/60 bg-purple-950/20 hover:bg-purple-950/30 rounded-full px-4 py-2.5">
                     <span className="text-white font-bold text-xs tracking-wide">Retreat and reassess</span>
                     <div className="flex items-center space-x-1 text-purple-400 font-mono text-[9px] font-bold">
                       <Zap className="w-2.5 h-2.5" /> <span>TRICK</span>
                     </div>
                   </button>
                 </div>
               )}
               <div className="pt-2 flex justify-between items-center">
                   <span className="text-[#475569] font-mono text-[8px] uppercase tracking-widest flex items-center">
                     <div className="w-1.5 h-2 bg-cyan-700 mr-1.5 rounded-sm" /> DM REASONING
                   </span>
                   <ChevronRight className="w-3 h-3 text-[#475569] rotate-90" />
               </div>
             </div>
           </div>
         )}
         
         {/* 4. RECAP SCREEN */}
         {activeScreen === 'recap' && (
           <div className="flex-1 bg-[#090F16] flex flex-col font-sans pt-12 pb-8 relative overflow-y-auto selection:bg-red-500/30 px-5">
             <div className="absolute top-0 inset-x-0 h-64 bg-gradient-to-b from-red-950/30 to-transparent pointer-events-none" />
             
             <div className="w-full flex flex-col relative z-10 pt-6">
               <div className="w-14 h-14 bg-red-950/60 border border-red-900/50 mx-auto rounded-2xl flex items-center justify-center mb-5 shadow-[0_0_30px_rgba(153,27,27,0.3)]">
                 <Skull className="w-6 h-6 text-red-500/90" />
               </div>
               
               <h1 className="text-3xl font-extrabold text-red-400 text-center mb-1 tracking-tight drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]">Fallen in the Dark</h1>
               <div className="text-[10px] font-mono text-gray-500 tracking-[0.2em] uppercase text-center mb-5">
                 {run.playerClass?.name || 'EXPLORER'} · END OF RUN
               </div>
               
               <div className="flex justify-center mb-5">
                 <div className="flex items-center space-x-1 border border-red-900/50 bg-red-950/20 text-red-400 text-[10px] px-3 py-1 rounded-full font-mono">
                    <Star className="w-3 h-3 text-red-500" /> <span>The Iron Blade</span>
                 </div>
               </div>
               
               <div className="bg-[#0F172A] border border-[#1E293B] rounded-xl p-4 mb-4">
                 <p className="text-[#94A3B8] font-mono text-[11px] leading-relaxed">
                   Three floors in, you were rewriting the rules. Floor 2 was where the math caught up. But you fought beautifully.
                 </p>
               </div>
               
               <div className="grid grid-cols-2 gap-2 mb-2">
                 <div className="bg-[#0F172A] border border-[#1E293B] rounded-xl p-3 flex flex-col justify-between">
                   <div className="flex items-center space-x-1.5 text-[#475569] font-mono text-[8px] uppercase tracking-wider mb-2">
                     <Layers className="w-3.5 h-3.5 text-gray-500" /> <span>FLOORS</span>
                   </div>
                   <div className="text-2xl font-bold font-mono text-white leading-none">1 <span className="text-[#475569]">/ 5</span></div>
                 </div>
                 
                 <div className="bg-[#0F172A] border border-[#1E293B] rounded-xl p-3 flex flex-col justify-between">
                   <div className="flex items-center space-x-1.5 text-[#475569] font-mono text-[8px] uppercase tracking-wider mb-2">
                     <Heart className="w-3.5 h-3.5 text-red-900" /> <span>FINAL HP</span>
                   </div>
                   <div className="text-2xl font-bold font-mono text-white leading-none">0 <span className="text-[#475569]">/ 10</span></div>
                 </div>
                 
                 <div className="bg-[#0F172A] border border-[#1E293B] rounded-xl p-3 flex flex-col justify-between">
                   <div className="flex items-center space-x-1.5 text-[#475569] font-mono text-[8px] uppercase tracking-wider mb-2">
                     <Coins className="w-3.5 h-3.5 text-yellow-600/50" /> <span>GOLD</span>
                   </div>
                   <div className="text-2xl font-bold font-mono text-white leading-none">{run.gold}</div>
                 </div>
                 
                 <div className="bg-[#0F172A] border border-[#1E293B] rounded-xl p-3 flex flex-col justify-between">
                   <div className="flex items-center space-x-1.5 text-[#475569] font-mono text-[8px] uppercase tracking-wider mb-2">
                     <Package className="w-3.5 h-3.5 text-gray-500" /> <span>ITEMS</span>
                   </div>
                   <div className="text-2xl font-bold font-mono text-white leading-none">1</div>
                 </div>
               </div>
               
               <div className="bg-[#0F172A] border border-[#1E293B] rounded-xl p-3 flex justify-between items-center mb-4">
                 <div className="flex flex-col">
                   <div className="font-mono text-[8px] text-[#475569] uppercase tracking-widest mb-1.5">DOMINANT PLAY STYLE</div>
                   <div className="flex items-center font-bold text-white text-[13px]">
                     <div className="w-2.5 h-2.5 bg-red-400 rounded-full mr-2 shadow-[0_0_8px_rgba(248,113,113,0.6)]" /> Aggressive
                   </div>
                 </div>
               </div>
               
               <div className="mb-6">
                 <div className="font-mono text-[8px] text-[#475569] uppercase tracking-widest mb-1.5 px-1">ITEMS CARRIED</div>
                 <div className="bg-[#0F172A] border border-[#1E293B] rounded-xl p-3 pt-2.5 flex items-center space-x-3">
                   <div className="w-8 h-8 rounded border border-[#1E293B] bg-[#090F16] flex items-center justify-center shrink-0">
                      <Package className="w-3.5 h-3.5 text-gray-400" />
                   </div>
                   <div className="flex flex-col">
                      <h4 className="text-white font-bold text-[12px] leading-tight mb-0.5">Sentinel's Cracked Eye</h4>
                      <div className="text-gray-500 text-[9px] font-mono leading-tight">+2 to the first strike of each combat encounter</div>
                   </div>
                 </div>
               </div>
               
               <button onClick={() => setActiveScreen('home')} className="w-full bg-[#387478] hover:bg-cyan-700 text-white rounded-full py-3.5 flex justify-center items-center font-bold text-sm transition-all shadow-lg border border-cyan-500/20 mb-2">
                 <RotateCcw className="w-3.5 h-3.5 mr-2 stroke-[2.5]" /> Play Again
               </button>
               <div className="text-center text-[9px] font-mono text-[#334155] tracking-wider mb-8 sm:mb-6">
                 Resets all state · New run · New AI story
               </div>
             </div>
           </div>
         )}
      </div>
    </div>
  )
}
