import React, { useEffect } from 'react';
import { Swords, Hexagon, Clock, Trophy, Zap, Star, ChevronRight } from 'lucide-react';
import { useGameStore } from '../store';
import { audioHaptics } from '../audio';
import { loadProfile } from '../profileStorage';

export function HomeScreen() {
  const { setActiveScreen, setProfile, resetRun, profile } = useGameStore();

  useEffect(() => {
    resetRun();
    // Load the real persisted profile on every visit to HomeScreen
    const saved = loadProfile();
    setProfile(saved);
  }, []);

  const isFirstRun = (profile?.runsCompleted ?? 0) === 0;

  return (
    <div className="flex-1 bg-[#090F16] flex flex-col items-center justify-center p-6 pt-safe pb-10 text-white relative overflow-hidden">
      {/* Ambient glow */}
      <div className="absolute top-[20%] w-64 h-64 bg-cyan-900/20 rounded-full blur-[80px]" />

      <div className="relative z-10 w-full flex flex-col items-center">
        {/* Icon */}
        <div className="w-16 h-16 bg-gradient-to-br from-cyan-600 to-cyan-900 rounded-[20px] flex items-center justify-center mb-5 shadow-[0_0_30px_rgba(34,211,238,0.25)]">
          <Swords className="text-white w-8 h-8" />
        </div>

        {/* Title */}
        <h1 className="text-4xl font-extrabold mb-1 tracking-tight">Realm Explorer</h1>
        <div className="flex items-center space-x-2 text-cyan-500 text-[10px] tracking-[0.2em] font-mono mb-2">
          <Hexagon className="w-3 h-3" />
          <span>AGENTIC DUNGEON CRAWLER</span>
          <Hexagon className="w-3 h-3" />
        </div>
        <p className="text-[#64748B] text-[11px] mb-8 text-center max-w-[200px]">
          Every encounter generated by Gemini AI in real time.
        </p>

        {/* Profile card */}
        <div className="w-full bg-[#0F172A]/80 backdrop-blur-sm border border-[#1E293B] rounded-xl overflow-hidden mb-8 shadow-xl">
          {/* Card header */}
          <div className="flex justify-between items-center px-4 py-2 border-b border-[#1E293B] bg-[#050B14]">
            <div className="flex items-center space-x-2">
              <div className="w-5 h-5 bg-blue-500 rounded-full" />
              <span className="font-mono text-[10px] text-gray-400 tracking-wider">EXPLORER PROFILE</span>
            </div>
            <div className="flex items-center space-x-1">
              <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full shadow-[0_0_5px_rgba(16,185,129,0.5)]" />
              <span className="font-mono text-[10px] text-emerald-500">
                {isFirstRun ? 'NEW' : 'ACTIVE'}
              </span>
            </div>
          </div>

          {isFirstRun ? (
            /* ── First-time user: no stats yet ── */
            <div className="px-4 py-5 text-center">
              <p className="text-[#475569] font-mono text-[11px] leading-relaxed">
                No runs yet. Complete a run to<br />build your explorer profile.
              </p>
            </div>
          ) : (
            <>
              {/* Stats grid */}
              <div className="grid grid-cols-3 divide-x divide-[#1E293B] text-center p-3">
                <div className="flex flex-col items-center">
                  <Clock className="w-4 h-4 text-gray-500 mb-1" />
                  <div className="font-bold text-lg mb-0.5">{profile!.runsCompleted}</div>
                  <div className="font-mono text-[9px] text-[#475569]">RUNS</div>
                </div>
                <div className="flex flex-col items-center">
                  <Trophy className="w-4 h-4 text-gray-500 mb-1" />
                  <div className="font-bold text-lg mb-0.5">{profile!.bestDepth}</div>
                  <div className="font-mono text-[9px] text-[#475569]">BEST DEPTH</div>
                </div>
                <div className="flex flex-col items-center">
                  <Zap className="w-4 h-4 text-gray-500 mb-1" />
                  <div className="font-bold text-lg mb-0.5">{profile!.averageStyle}</div>
                  <div className="font-mono text-[9px] text-[#475569]">STYLE</div>
                </div>
              </div>

              {/* Earned titles */}
              {profile!.allTimeTitles.length > 0 && (
                <div className="px-3 pb-3">
                  <div className="font-mono text-[9px] text-[#475569] mb-1.5">EARNED TITLES</div>
                  <div className="flex flex-wrap gap-1.5">
                    {profile!.allTimeTitles.map(t => (
                      <div key={t} className="flex items-center space-x-1 border border-cyan-900/50 bg-cyan-950/20 text-cyan-300 text-[10px] px-2 py-1 rounded-full">
                        <Star className="w-3 h-3 text-cyan-500" /> <span>{t}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </>
          )}
        </div>

        {/* Powered by */}
        <div className="flex items-center space-x-2 text-[10px] font-mono text-gray-500 mb-2">
          <div className="w-2 h-2 bg-emerald-400 rounded-full shadow-[0_0_5px_rgba(16,185,129,0.5)]" />
          <span>Powered by <span className="text-cyan-400 font-bold">Gemini 2.0 Flash</span></span>
        </div>

        {/* CTA */}
        <button
          onClick={() => { audioHaptics.click(); setActiveScreen('classSelect'); }}
          className="w-full bg-gradient-to-r from-cyan-600 to-cyan-500 hover:from-cyan-500 hover:to-cyan-400 text-white rounded-2xl py-5 px-8 flex justify-center items-center gap-2 font-bold text-sm shadow-lg mb-3 transition-all">
          <Swords className="w-4 h-4" /> {isFirstRun ? 'Start Your First Run' : 'Enter the Dungeon'} <ChevronRight className="w-4 h-4" />
        </button>
        <div className="text-[10px] font-mono text-[#334155] tracking-wider text-center">
          AI-powered · Every run is unique · 5 floors deep
        </div>
      </div>
    </div>
  );
}
